### ISSUE TITLE
Issue: White Label module showing `white_label.white_label_title` in admin but returns 404 on click

### ISSUE THREAD

**Issue by MonsteraCompany** [InvoiceShelf/module-whitelabel#7]
Hi,

I'm trying to use the **White Label** module with InvoiceShelf (latest `nightly` image).
I've updated the `docker-compose.yml` file to mount my local modules directory like this:

```yaml
services:
  invoiceshelf:
    image: invoiceshelf/invoiceshelf:nightly
    container_name: invoiceshelf
    ports:
      - 90:80
    volumes:
      - ./invoiceshelf_sqlite/data:/data
      - ./invoiceshelf_sqlite/conf:/conf
      - ./modules:/var/www/html/InvoiceShelf/Modules  # <- Added this line
    networks:
      - invoiceshelf
    environment:
        (...)
    restart: unless-stopped

networks:
  invoiceshelf:
```

My project directory is structured as follows:

```
/
├── docker-compose.yml
├── modules
│   └── WhiteLabel
│       ├── package.json
│       └── (...)
```

When I go to the **admin interface**, I can see the module listed.
However, its label appears as: `white_label.white_label_title` (instead of a readable name), and when I click on it, it leads to a **404 error page**.

So it seems the module is partially detected (probably via the filesystem), but not correctly loaded or registered.

Any ideas on what I might be missing or misconfigured?

Thanks in advance for your help!
